filegroup(
    name = "headers-helper",
    srcs = [
        "//tests/helper:assert.h",
        "//tests/helper:binomial_test.h",
        "//tests/helper:common.h",
        "//tests/helper:counter.h",
        "//tests/helper:distance.h",
        "//tests/helper:operator.h",
        "//tests/helper:pprint.h",
        "//tests/helper:random.h",
        "//tests/helper:tests.h",
    ],
    visibility = ["//visibility:public"],
)
